language: node_js
node_js:
  - node # latest stable
  - 10
cache:
  directories:
    - node_modules
install:
  - npm prune
  - npm install
script:
  - npm run lint
  - npm uninstall resume-cli
  - npm install --global --force resume-cli@1.2.3
  - npm install --global --force jsonresume-theme-rocketspacer
  - resume export --theme rocketspacer public/index.html
deploy:
  # https://docs.travis-ci.com/user/deployment/pages
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master
    node: 10
